buildscript {
    

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        jcenter()
        google()
    }
    dependencies {
        classpath files("game.jar")
    }
}

allprojects {

    version = '1.0'
    ext {
        appName = "bloons-tower-defence"
        gdxVersion = '1.9.10'
        roboVMVersion = '2.3.8'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
        google()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

task packActors {
    doLast {
        def inputDir = new File(project.buildDir, "actor_inputs")
        inputDir.mkdirs()
        copy {
            from "core/assets/img/characters"
            include "*.png"
            exclude "characters.png"
            into inputDir
        }
        copy {
            from "core/assets/img/projectiles"
            include "*.png"
            exclude "projectiles.png"
            into inputDir
        }
        copy {
            from "core/assets/img/spellcards"
            include "*.png"
            into inputDir
        }
        
        def settings = new com.badlogic.gdx.tools.texturepacker.TexturePacker.Settings()
        settings.maxWidth = 2048
        settings.maxHeight = 2048

        com.badlogic.gdx.tools.texturepacker.TexturePacker.process(
            settings,
            inputDir.getAbsolutePath(),
            file("core/assets").getAbsolutePath(),
            "actors"
        )
    }
}

project(":desktop") {
    apply plugin: "java-library"


    dependencies {
        implementation project(":core")
        api files("${rootProject.projectDir}/game.jar")
    }
}

project(":core") {
    apply plugin: "java-library"

    processResources.dependsOn rootProject.packActors

    dependencies {
        api files("${rootProject.projectDir}/game.jar")
    }
}
