apply plugin: "java"

sourceCompatibility = 8
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

sourceSets {
    main {
        java {
            srcDirs = [ "src/" ]
            exclude "test/**"
        }
    }
    test {
        java {
            srcDirs = [ "src/test/java" ]
        }
    }
}

test {
    workingDir = new File(projectDir, "assets")
}

dependencies {
    testImplementation "junit:junit:4.13.2"
    testImplementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion"
    testImplementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
}
