package com.hongbao.bloons.events;

import com.hongbao.bloons.actors.BloonActor;
import com.hongbao.bloons.helpers.BloonPoppedResult;

/**
 * Event listener interface for balloon and game progression events.
 */
public interface BloonEventListener {

    /**
     * Callback invoked synchronously when a balloon is damaged without popping.
     *
     * @param bloonActor the balloon actor taking damage
     * @param damage amount of damage inflicted
     */
    default void onBloonDamaged(BloonActor bloonActor, int damage) {}

    /**
     * Callback invoked synchronously when a balloon pops.
     *
     * @param bloonActor the balloon actor being popped
     * @param result details of cash and bloons generated by popping
     */
    default void onBloonPopped(BloonActor bloonActor, BloonPoppedResult result) {}

    /**
     * Callback invoked synchronously when a level is cleared.
     *
     * @param level the level number cleared
     */
    default void onLevelCleared(int level) {}
}
